### ISSUE TITLE
Peer to peer code review: Morning Session

### ISSUE THREAD

**Issue by nevisende** [Mithi-code/leaderboard#6]
You've done a great job 💯.Congrutilations 🎉🎉. But I can say a few things you can improve your code:
https://github.com/Mithi-code/leaderboard/blob/3f57d5e11020ece972e2e01992d5e562cb998ed5/src/index.html#L10
- You should use here the main tag because you don't have much more than one section.
https://github.com/Mithi-code/leaderboard/blob/3f57d5e11020ece972e2e01992d5e562cb998ed5/src/api.js#L4
- You don't need to write await again because before this line JavaScript waits for its response If you check you can see.
That is it for me. Happy coding 🙂🙂

**Comment by NasKhalil** [comment]
Hi @Mithi-code! just update your read me file your live demo link doesn't work.

Good job & happy coding 🚀

**Comment by youmari** [comment]
### Hi @Mithi-code 
#### Your code is clean and professional and following the best practices 💯 God job for that 🥇 

- #### I noticed an irrelevant keyword in your callback function that doesn't do anything so you can remove it in order to keep only relevant code 
https://github.com/Mithi-code/leaderboard/blob/3f57d5e11020ece972e2e01992d5e562cb998ed5/src/index.js#L13

**Comment by Mithi-code** [comment]
Thanks for your feedback

Closing #6
